# Nombre de la aplicación
spring.application.name=Practica01

# Puerto solicitado para la práctica
server.port=91

# Formato de fecha y hora para los logs en consola
logging.pattern.dateformat=dd HH:mm

# Nivel de detalle de los mensajes en consola
logging.level.root=TRACE

# Evita mostrar el banner de Spring al ejecutar
spring.main.banner-mode=off

# En desarrollo se desactiva el caché de Thymeleaf
spring.thymeleaf.cache=false

# Configuración de internacionalización
spring.messages.basename=messages
spring.messages.encoding=UTF-8